# Generated by Django 5.2.13 on 2026-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_customer_store_created_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_store_created_desc_idx',
        ),
    ]
