# Generated by Django 5.2.12 on 2026-03-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Leaf or intermediate category this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='navbar_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent category; null means top-level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order among siblings.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Slug unique per store for this category.', max_length=100),
        ),
        migrations.DeleteModel(
            name='NavbarCategory',
        ),
    ]
