# Generated by Django 5.2.13 on 2026-04-28 04:59

import engine.core.media_upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_prepayment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=engine.core.media_upload_paths.tenant_category_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=engine.core.media_upload_paths.tenant_product_main_upload_to),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=engine.core.media_upload_paths.tenant_product_gallery_upload_to),
        ),
    ]
