# Generated by Django 5.2.13 on 2026-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_storefront_composite_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_store_active_status_order_idx',
        ),
    ]
