# Generated by Django 5.2.12 on 2026-03-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDashboardStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('bucket', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month')], db_index=True, default='day', max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats_snapshots', to='stores.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'start_date', 'end_date', 'bucket'), name='uniq_dashboardstatsnapshot_store_range_bucket')],
            },
        ),
    ]
