# Generated by Django 5.2.12 on 2026-03-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_variant_unique_constraints'),
        ('products', '0002_remove_productvariant_stock_quantity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cartitem_cart_variant_when_set',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cartitem_cart_product_size_no_variant',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
