# Generated by Django 5.2.13 on 2026-04-08 10:22

import django.db.models.deletion
import engine.core.media_upload_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier used in APIs and URLs (e.g. str_xxx).', max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe unique slug (globally unique); may change for branding. Not used in SKUs.', max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Stable uppercase alphanumeric tenant code for variant SKUs; set once and never changes.', max_length=10, unique=True)),
                ('store_type', models.CharField(blank=True, help_text='Store type/category (e.g. Fashion, Retail, E-commerce). Max 4 words.', max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_delete', 'Pending delete')], db_index=True, default='active', help_text='Lifecycle state; is_active is kept in sync for legacy queries.', max_length=20)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True)),
                ('delete_at', models.DateTimeField(blank=True, db_index=True, help_text='Scheduled permanent deletion time (INACTIVE or PENDING_DELETE).', null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, help_text='Last tenant API activity (ACTIVE stores only).', null=True)),
                ('inactive_recovery_reminder_sent_at', models.DateTimeField(blank=True, help_text='Idempotency: INACTIVE reminder email (7 days before delete_at).', null=True)),
                ('pending_delete_2d_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('pending_delete_1d_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_version', models.PositiveIntegerField(default=0, help_text='Monotonic counter incremented on every status transition; guards Celery jobs.')),
                ('is_active', models.BooleanField(default=True)),
                ('owner_name', models.CharField(help_text='Full name of the store owner.', max_length=255)),
                ('owner_email', models.EmailField(help_text='Email address of the store owner.', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=engine.core.media_upload_paths.tenant_store_logo_upload_to)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('currency_symbol', models.CharField(blank=True, default='৳', max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(help_text='Account that owns this store (at most one store per user).', on_delete=django.db.models.deletion.PROTECT, related_name='owned_store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. sak_xxx).', max_length=32, unique=True)),
                ('key_hash', models.CharField(db_index=True, help_text='HMAC-SHA256 digest of API key material.', max_length=64, unique=True)),
                ('key_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('key_last4', models.CharField(blank=True, default='', max_length=4)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('key_type', models.CharField(choices=[('public', 'Public'), ('secret', 'Secret')], db_index=True, default='public', max_length=16)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDeletionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. dlj_xxx).', max_length=32, unique=True)),
                ('store_public_id_snapshot', models.CharField(db_index=True, help_text='Store public_id snapshot taken at deletion request time.', max_length=32)),
                ('store_id_snapshot', models.BigIntegerField(db_index=True, help_text='Store primary key snapshot taken at deletion request time.')),
                ('delete_at_snapshot', models.DateTimeField(blank=True, help_text='Expected hard-delete time when the job was created (scheduled deletion).', null=True)),
                ('lifecycle_version_snapshot', models.PositiveIntegerField(default=0, help_text='Store lifecycle_version at scheduling time; worker aborts if mismatch.')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped_not_due', 'Skipped (not yet due)')], db_index=True, default='pending', max_length=20)),
                ('current_step', models.CharField(blank=True, default='', max_length=120)),
                ('redirect_route', models.CharField(default='/onboarding', help_text='Frontend route to redirect after deletion is finalized.', max_length=64)),
                ('next_store_public_id', models.CharField(blank=True, help_text='Optional next active store public_id for the issuing JWTs.', max_length=32, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_deletion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreDeletionOtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_otp_challenges', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_deletion_otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLifecycleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_public_id', models.CharField(db_index=True, max_length=32)),
                ('action', models.CharField(choices=[('STORE_REMOVE', 'Store remove'), ('STORE_DELETE_OTP_SENT', 'Delete OTP sent'), ('STORE_DELETE_SCHEDULED', 'Delete scheduled'), ('STORE_DELETE_SKIPPED_NOT_DUE', 'Delete skipped (not due)'), ('STORE_DELETE_STARTED', 'Delete started'), ('STORE_DELETE_SUCCESS', 'Delete success'), ('STORE_DELETE_FAILED', 'Delete failed'), ('STORE_DELETE_FORCED', 'Forced delete invoked'), ('STORE_RESTORE', 'Store restore'), ('STORE_INACTIVITY_PENDING', 'Inactivity pending delete')], db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_audit_logs', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier used in APIs and URLs (e.g. mbr_xxx).', max_length=32, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreRestoreChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('purpose', models.CharField(choices=[('restore_inactive', 'Restore inactive'), ('restore_pending_delete', 'Restore pending delete')], db_index=True, max_length=40)),
                ('owner_code_hash', models.CharField(max_length=64)),
                ('contact_code_hash', models.CharField(max_length=64)),
                ('single_channel', models.BooleanField(default=False, help_text='True when owner_email equals contact_email; one code verifies both.')),
                ('owner_verified_at', models.DateTimeField(blank=True, null=True)),
                ('contact_verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_challenges', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_enabled', models.JSONField(blank=True, default=dict, help_text='Feature/module flags for this store (e.g. products, orders).')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Default low-stock alert threshold for inventory.')),
                ('extra_field_schema', models.JSONField(blank=True, default=list, help_text='Extra field definitions for products only: [{id, entityType, name, fieldType, required, order, options}]')),
                ('email_notify_owner_on_order_received', models.BooleanField(default=False, help_text='Premium: send email to store when a new order is placed.')),
                ('email_customer_on_order_confirmed', models.BooleanField(default=False, help_text='Premium: email customer when the order is sent to courier (dispatch).')),
                ('public_api_enabled', models.BooleanField(default=False, help_text='Allow public storefront read endpoints without API key for this store.')),
                ('storefront_public', models.JSONField(blank=True, default=dict, help_text='Public storefront-only data: theme_settings, country, seo, policy_urls, social_links, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Store settings',
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'created_at'], name='stores_stor_is_acti_a0dd20_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status', 'delete_at'], name='stores_stor_status_2e6286_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status', 'last_activity_at'], name='stores_stor_status_30c942_idx'),
        ),
        migrations.AddIndex(
            model_name='storeapikey',
            index=models.Index(fields=['store', 'is_active', 'created_at'], name='stores_stor_store_i_d05ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='storedeletionjob',
            index=models.Index(fields=['user', 'status'], name='stores_stor_user_id_f7a254_idx'),
        ),
        migrations.AddIndex(
            model_name='storedeletionotpchallenge',
            index=models.Index(fields=['store', 'expires_at'], name='stores_stor_store_i_c426f0_idx'),
        ),
        migrations.AddIndex(
            model_name='storelifecycleauditlog',
            index=models.Index(fields=['store_public_id', '-created_at'], name='stores_stor_store_p_cb63ef_idx'),
        ),
        migrations.AddIndex(
            model_name='storemembership',
            index=models.Index(fields=['store', 'role'], name='stores_stor_store_i_845485_idx'),
        ),
        migrations.AddIndex(
            model_name='storemembership',
            index=models.Index(fields=['user', 'created_at'], name='stores_stor_user_id_434953_idx'),
        ),
        migrations.AddConstraint(
            model_name='storemembership',
            constraint=models.UniqueConstraint(fields=('user', 'store'), name='uniq_store_membership_user_store'),
        ),
        migrations.AddIndex(
            model_name='storerestorechallenge',
            index=models.Index(fields=['store', 'purpose', 'expires_at'], name='stores_stor_store_i_bb07ab_idx'),
        ),
    ]
