# Generated by Django 5.2.12 on 2026-03-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='email_customer_on_order_confirmed',
            field=models.BooleanField(default=False, help_text='Premium: email customer when the order is sent to courier (dispatch).'),
        ),
    ]
