# Generated by Django 5.2.13 on 2026-04-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedeletionjob',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the worker began executing; used to compute lease expiry.', null=True),
        ),
        migrations.AlterField(
            model_name='storelifecycleauditlog',
            name='action',
            field=models.CharField(choices=[('STORE_REMOVE', 'Store remove'), ('STORE_DELETE_OTP_SENT', 'Delete OTP sent'), ('STORE_DELETE_SCHEDULED', 'Delete scheduled'), ('STORE_DELETE_SKIPPED_NOT_DUE', 'Delete skipped (not due)'), ('STORE_DELETE_STARTED', 'Delete started'), ('STORE_DELETE_SUCCESS', 'Delete success'), ('STORE_DELETE_FAILED', 'Delete failed'), ('STORE_DELETE_FORCED', 'Forced delete invoked'), ('STORE_DELETE_ALREADY_MISSING', 'Store already missing'), ('STORE_RESTORE', 'Store restore'), ('STORE_INACTIVITY_PENDING', 'Inactivity pending delete')], db_index=True, max_length=40),
        ),
    ]
