# Generated by Cursor on 2026-03-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreDeletionJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "store_public_id_snapshot",
                    models.CharField(
                        db_index=True,
                        help_text="Store public_id snapshot taken at deletion request time.",
                        max_length=32,
                    ),
                ),
                (
                    "store_id_snapshot",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Store primary key snapshot taken at deletion request time.",
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_step", models.CharField(blank=True, default="", max_length=120)),
                (
                    "redirect_route",
                    models.CharField(
                        default="/onboarding",
                        help_text="Frontend route to redirect after deletion is finalized.",
                        max_length=64,
                    ),
                ),
                (
                    "next_store_public_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional next active store public_id for the issuing JWTs.",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_deletion_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "status"], name="stores_storedeletionjob_user_statu_idx")],
            },
        ),
    ]

