# Generated by Django 5.2.12 on 2026-03-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_deletion_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storedeletionjob',
            new_name='stores_stor_user_id_f7a254_idx',
            old_name='stores_storedeletionjob_user_statu_idx',
        ),
    ]
