# Generated by Django 5.2.12 on 2026-04-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storedeletionjob_delete_at_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='store',
            new_name='stores_stor_status_2e6286_idx',
            old_name='stores_stor_status__idx',
        ),
        migrations.RenameIndex(
            model_name='store',
            new_name='stores_stor_status_30c942_idx',
            old_name='stores_stor_status__2_idx',
        ),
        migrations.RenameIndex(
            model_name='storerestorechallenge',
            new_name='stores_stor_store_i_bb07ab_idx',
            old_name='stores_stor_store_i_idx',
        ),
    ]
