# Generated by Django 5.2.12 on 2026-03-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_code_data_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(help_text='URL-safe unique slug (globally unique); may change for branding. Not used in SKUs.', max_length=100, unique=True),
        ),
    ]
