# Generated by Django 5.2.12 on 2026-03-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_domain'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='domain',
            new_name='stores_doma_domain_5e34ee_idx',
            old_name='stores_doma_domain_0b7b1b_idx',
        ),
    ]
