# Generated by Django 5.2.12 on 2026-04-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_storelifecycleauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storedeletionotpchallenge',
            new_name='stores_stor_store_i_c426f0_idx',
            old_name='stores_stord_store_i_7c8f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='storelifecycleauditlog',
            new_name='stores_stor_store_p_cb63ef_idx',
            old_name='stores_storeli_store_p_idx',
        ),
    ]
