# Generated by Django 5.2.13 on 2026-04-28 04:59

import engine.core.media_upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_banner_image_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=engine.core.media_upload_paths.tenant_banner_image_upload_to),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=engine.core.media_upload_paths.tenant_banner_gallery_image_upload_to),
        ),
    ]
