# Generated by Django 5.2.13 on 2026-04-29 08:25

import django.db.models.deletion
import engine.core.media_upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_add_started_at_and_already_missing_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. pop_xxx).', max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=255)),
                ('button_link', models.CharField(blank=True, max_length=500)),
                ('delay_seconds', models.PositiveIntegerField(default=5)),
                ('show_frequency', models.CharField(choices=[('session', 'Once per session'), ('daily', 'Once per day'), ('always', 'Always')], default='session', max_length=10)),
                ('show_on_all_pages', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popups', to='stores.store')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StorePopupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. pim_xxx).', max_length=32, unique=True)),
                ('image', models.ImageField(max_length=500, upload_to=engine.core.media_upload_paths.tenant_popup_image_upload_to)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='popups.storepopup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
