# Generated by Django 5.2.13 on 2026-04-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0001_initial'),
        ('stores', '0002_add_started_at_and_already_missing_action'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storepopup',
            constraint=models.UniqueConstraint(fields=('store',), name='popups_storepopup_store_unique'),
        ),
    ]
