# Generated by Cursor on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing_integrations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integrationeventsettings",
            name="track_purchase",
        ),
        migrations.RemoveField(
            model_name="integrationeventsettings",
            name="track_initiate_checkout",
        ),
        migrations.RemoveField(
            model_name="integrationeventsettings",
            name="track_view_content",
        ),
        migrations.RemoveField(
            model_name="integrationeventsettings",
            name="track_page_view",
        ),
        migrations.AddField(
            model_name="integrationeventsettings",
            name="track_order_created",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="integrationeventsettings",
            name="track_checkout_started",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="integrationeventsettings",
            name="track_product_detail_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="integrationeventsettings",
            name="track_search",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="integrationeventsettings",
            name="track_support_ticket",
            field=models.BooleanField(default=True),
        ),
    ]

