# Generated by Django 5.2.12 on 2026-04-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trashitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trashitem',
            new_name='core_trashi_store_i_a062e7_idx',
            old_name='core_trashi_store_i_7a8b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='trashitem',
            new_name='core_trashi_store_i_9d49d3_idx',
            old_name='core_trashi_store_i_9d0e1f_idx',
        ),
    ]
