# Generated by Django 5.2.12 on 2026-03-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_activi_created_7d4c0f_idx_core_activi_created_3d0bd9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardbranding',
            name='admin_name',
            field=models.CharField(default='E-commerce Store', max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardbranding',
            name='currency_symbol',
            field=models.CharField(blank=True, default='$', max_length=10),
        ),
    ]
