# Generated by Django 5.2.13 on 2026-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_platform_notification_window_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='platformnotification',
            name='platformnotif_active_window_idx',
        ),
    ]
