# Generated by Django 5.2.12 on 2026-04-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Structured config: {"limits": {"max_products": N}, "features": {"basic_analytics": bool, ...}}'),
        ),
    ]
