# Generated by Django 5.2.13 on 2026-04-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_pending_status_and_plan_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_review', 'Pending review'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
    ]
