# Generated by Django 5.2.12 on 2026-04-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_purchase_ledger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseledgeradjustment',
            new_name='orders_purc_store_i_170a2f_idx',
            old_name='orders_purch_store_o_adj_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseledgeradjustment',
            new_name='orders_purc_store_i_4cc60a_idx',
            old_name='orders_purch_store_c_adj_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseledgerentry',
            new_name='orders_purc_store_i_365977_idx',
            old_name='orders_purch_store_i_ledger_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseledgerentry',
            new_name='orders_purc_store_i_413dac_idx',
            old_name='orders_purch_store_o_ledger_idx',
        ),
    ]
