# Generated by Django 5.2.12 on 2026-03-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pricing_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_confirmation_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set when ORDER_CONFIRMED was sent after courier dispatch.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON audit snapshot of order pricing breakdown (lines + rollups + shipping).'),
        ),
    ]
