# Generated by Django 5.2.13 on 2026-04-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderexportjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderexportjob',
            new_name='orders_orde_store_i_5f7c90_idx',
            old_name='ordexp_store_status',
        ),
        migrations.RenameIndex(
            model_name='orderexportjob',
            new_name='orders_orde_expires_7f9b7f_idx',
            old_name='ordexp_expires',
        ),
    ]
