# Generated by Django 5.2.13 on 2026-04-23 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_denormalized_metrics'),
        ('orders', '0005_rename_ordexp_store_status_orders_orde_store_i_5f7c90_idx_and_more'),
        ('shipping', '0001_initial'),
        ('stores', '0002_add_started_at_and_already_missing_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store_id', 'created_at'], name='orders_store_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store_id', 'status', 'created_at'], name='orders_store_status_creat_idx'),
        ),
    ]
