# Generated by Django 5.2.13 on 2026-04-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_composite_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_store_created_idx',
        ),
    ]
