# Generated by Django 5.2.13 on 2026-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_index_consolidation'),
        ('stores', '0002_add_started_at_and_already_missing_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, editable=False, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('store', 'order_number')},
        ),
    ]
