# Generated by Django 5.2.13 on 2026-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_add_order_store_status_created_desc_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_store_status_created_desc_idx',
        ),
    ]
