# Generated by Django 5.2.13 on 2026-04-28 04:59

import engine.core.media_upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=engine.core.media_upload_paths.tenant_blog_featured_image_upload_to),
        ),
    ]
