# Generated by Django 5.2.13 on 2026-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_add_blog_store_visibility_published_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_store_deleted_public_published_idx',
        ),
    ]
