# Generated by Django 5.2.13 on 2026-04-28 04:59

import engine.core.media_upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticketattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=engine.core.media_upload_paths.tenant_support_attachment_upload_to),
        ),
    ]
