# Generated by Django 5.2.13 on 2026-04-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fraudchecklog',
            new_name='fraud_check_store_i_9d7b97_idx',
            old_name='fraud_check_store_norm_phone_idx',
        ),
    ]
