# Generated by Django 5.2.12 on 2026-04-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertwofactorchallenge',
            name='flow',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register')], max_length=20),
        ),
    ]
