# Generated by Django 5.2.12 on 2026-03-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_two_factor_recovery_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usertwofactorrecoverycode',
            new_name='accounts_us_user_id_b95528_idx',
            old_name='accounts_tfr_usr_used_exp',
        ),
        migrations.AlterField(
            model_name='usertwofactorrecoverycode',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. prd_xxx).', max_length=32, unique=True),
        ),
    ]
