# Generated by Django 5.2.12 on 2026-03-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_identity_not_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='per_identity_max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Max successful usages per customer identity within this store (phone > email > store_session_id).', null=True),
        ),
    ]
