# Generated by Django 5.2.12 on 2026-03-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_remove_couponusage_store_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='per_identity_max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Max successful usages per customer identity within this store (phone > email).', null=True),
        ),
    ]
